  [[main]]
    name = 'Home'
    pageRef = '/'
    weight = 10


  [[main]]
    name = 'About Us'
    pageRef ='/about_us/'
    weight = 50

  [[main]]
    name='Docs'
    identifier='guides'
    url='/doc/'
    weight=70
  