############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Research"
url = "/research"
weight = 3

[[main]]
name = "Projects"
url = "/projects"
weight = 4

[[main]]
name = "Publications"
url = "/publications"
weight = 5

[[main]]
name = "Team"
url = "/authors"
weight = 6


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

